feat: 인풋 컴포넌트 추가
12-Pair-Programming/Dang-il pull request #8
Opened 2024-04-17 13:25 UTC by tead7

## :grin:주요 변경 사항

- 인풋 컴포넌트를 추가하였습니다.
-사용법입니다.
  text = 제목
  placeholder = 피스홀더
  type = 타입
  width = 길이
  isError = 에러 연동
  errorText = 에러 메세지 연동
  countText = 단위

## 📄스크린샷
![캡처인풋](https://github.com/12-Pair-Programming/Dang-il/assets/94046941/a0dc0706-2c9d-4f60-a390-7d16bde618cf)

## :pencil:전달사항(세심하게 봐야 할 부분 / 고민점)

- 에러 관련 기능은 직접 추가하셔야합니다. (없으면 안 쓰셔도 작동합니다!)
- 패스워드 타입을 쓰면 눈표시가 생깁니다.

2024-04-17 14:50 UTC, Seoin02 requested changes
고생하셨습니다 당신은 input의 달인!! 수정사항 확인하고 알려주셔요~~

2024-04-17 14:50 UTC, Seoin02 commented on shared/@common/ui/input/input.tsx
> +  const [inputType, setInpuType] = useState(type);
setInputType 오타 수정하면 좋을 듯 합니다

2024-04-17 14:50 UTC, Seoin02 commented on shared/@common/ui/input/input.tsx
> +    setInpuType((prevType) => (prevType === 'password' ? 'text' : 'password'));
여기 오타도 함께 수정하면 좋을 것 같아요~

2024-04-17 14:50 UTC, Seoin02 commented on shared/@common/ui/input/input.tsx
> +            <img
NEXT.js 이미지 최적화를 써봐도 좋을 것 같아요

2024-04-18 01:59 UTC, rosedaily approved these changes

2024-04-18 03:07 UTC, Seoin02 approved these changes
수정사항 확인했습니다 고생하셨어여~~

2024-04-18 03:07 UTC, merged